apiVersion: v1
kind: Service
metadata:
  name: lb-prometheus
  namespace: dev
  labels:
    app: prometheus
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - name: "metricsx"
    protocol: TCP
    targetPort: "web"
    port: 9090    
  selector:
    app: prometheus
    tier: backend
