apiVersion: v1
kind: Service
metadata:
  name: lb-grafana
  namespace: dev
  labels:
    app: grafana
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - name: "metricsx"
    protocol: TCP
    targetPort: "web"
    port: 3000    
  selector:
    app: grafana
    tier: backend
