apiVersion: v1
kind: Service
metadata:
  name: lb-app-consumer
  namespace: dev
  labels:
    app: app-consumer
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    targetPort: http-server
    port: 8080
  selector:
    app: app-consumer
    tier: backend
