apiVersion: v1
kind: Service
metadata:
  name: lb-activemq
  namespace: dev
  labels:
    app: app-activemq
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - name: "brokerx"
    protocol: TCP
    targetPort: "broker"
    port: 61616
  - name: "adminx"
    protocol: TCP
    targetPort: "admin"
    port: 8161    
  selector:
    app: app-activemq
    tier: backend
