apiVersion: v1
kind: Service
metadata:
  name: lb-activemq
  namespace: dev
  labels:
    app: app-activemq
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - name: "openwirex"
    protocol: TCP
    targetPort: "openwire"
    port: 61616
  - name: "stompx"
    protocol: TCP
    targetPort: "stomp"
    port: 61613    
  - name: "adminx"
    protocol: TCP
    targetPort: "admin"
    port: 8161  
  - name: "metricsx"
    protocol: TCP
    targetPort: "metrics"
    port: 8080    
  selector:
    app: app-activemq
    tier: backend
